#pragma once

// Generated from docs/locales/es/draft-catalog.json.
// Machine-assisted candidate only; pending competent Spanish-language review.
#include <array>
#include <string_view>

namespace avida::web::localization {
struct SpanishEntry { std::string_view id; std::string_view source; std::string_view value; };
inline constexpr std::array<SpanishEntry, 285> SPANISH_CANDIDATE{{
  {"shell.app_title", "Avida-ED", "Avida-ED"},
  {"shell.lesson_title", "Mutation and genetic variation", "Mutación y variación genética"},
  {"shell.preview_label", "Avida 5 education preview", "Vista previa educativa de Avida 5"},
  {"shell.language.label", "Language", "Idioma"},
  {"shell.mode.population", "Population", "Población"},
  {"shell.mode.sequences", "Sequences", "Secuencias"},
  {"shell.mode.compare", "Compare runs", "Análisis"},
  {"shell.mode.population.accessible", "Population Mode", "Modo de Población"},
  {"shell.mode.organism.accessible", "Organism Mode", "Modo de Organismo"},
  {"shell.mode.compare.accessible", "Compare saved runs", "Comparar ejecuciones guardadas"},
  {"shell.mode.compare.disabled_help", "Complete two runs to compare them.", "Complete dos ejecuciones para compararlas."},
  {"shell.mode.compare.help", "Compare the completed runs.", "Comparar las ejecuciones completadas."},
  {"shell.sidepanel.run", "Run", "Ejecución"},
  {"shell.sidepanel.cell", "Cell", "Célula"},
  {"shell.sidepanel.saved_organisms", "Freezer", "Almacén"},
  {"shell.sidepanel.setup", "Setup", "Ajustes"},
  {"shell.sidepanel.population_stats.accessible", "Population Statistics", "Estadísticas de la población"},
  {"shell.sidepanel.organism_stats.accessible", "Organism Statistics", "Estadísticas del organismo"},
  {"shell.sidepanel.freezer.accessible", "Freezer", "Almacén"},
  {"shell.sidepanel.setup.help", "The lesson holds other settings fixed; see Experiment setup for the controlled values.", "La lección mantiene otros valores fijos; consulte la configuración del experimento para los valores controlados."},
  {"shell.grid.accessible", "Spatial grid population", "Población en cuadrícula espacial"},
  {"shell.grid.placement_help", "Drag organisms between the grid and freezer. Right-click an occupied cell for actions.", "Arrastre organismos entre la cuadrícula y el almacén. Haga clic derecho en una celda ocupada para ver las acciones disponibles."},
  {"shell.run", "Run", "Ejecutar"},
  {"shell.status.update", "Update {update}", "Actualización {update}"},
  {"shell.status.paused", "Paused at update {update}", "Pausado en la actualización {update}"},
  {"shell.pause", "Pause", "Pausar"},
  {"shell.step", "Step", "Paso"},
  {"shell.reset", "Start a new run", "Iniciar una nueva ejecución"},
  {"shell.step.accessible", "Advance one population update", "Avanzar una actualización de población"},
  {"shell.play.accessible", "Play at up to ten updates per second", "Reproducir hasta diez actualizaciones por segundo"},
  {"shell.pause.accessible", "Pause evolution", "Pausar la evolución"},
  {"shell.fast_forward", "Fast-forward", "Avance rápido"},
  {"shell.restart.help", "Start a new run; keep recorded results on the run shelf.", "Iniciar una nueva ejecución; mantener los resultados registrados en la estantería de la ejecución."},
  {"shell.organism_actions", "Organism actions", "Acciones del organismo"},
  {"shell.save_organism", "Save Organism", "Guardar organismo"},
  {"shell.remove_organism", "Remove Organism", "Eliminar organismo"},
  {"shell.staged_organisms.one", "{count} organism staged", "{count} organismo preparado"},
  {"shell.staged_organisms.other", "{count} organisms staged", "{count} organismos preparados"},
  {"shell.locale.pseudo_expanded", "Pseudo: expanded strings", "Pseudo: cadenas expandidas"},
  {"shell.locale.pseudo_rtl", "Pseudo: right-to-left layout", "Pseudo: diseño de derecha a izquierda"},
  {"lessons.mutation_variation.title", "Mutation and genetic variation", "Mutación y variación genética"},
  {"lessons.mutation_variation.question", "How does the mutation setting affect genetic variation over time?", "¿Cómo afecta la configuración de mutación a la variación genética a lo largo del tiempo?"},
  {"lessons.mutation_variation.richness", "Sequence richness is the number of distinct genome sequences present.", "La riqueza de secuencias es el número de secuencias genómicas distintas presentes."},
  {"lessons.mutation_variation.interpretation", "Compare runs as observations; one run does not establish a general outcome.", "Compare las ejecuciones como observaciones; una sola ejecución no establece un resultado general."},
  {"lesson.procedure", "Run the same 10 × 10 world with three fixed seeds. Compare observations; a single run is not a general result.", "Ejecute el mismo mundo de 10 × 10 con tres semillas fijas. Compare las observaciones; una sola ejecución no es un resultado general."},
  {"lesson.fixed_conditions", "The bundled ancestor, CPU and instruction set, grid, and ten logic-task rewards stay fixed. This is selection-active evolution, not neutral evolution.", "El ancestro incluido, el conjunto de instrucciones, la cuadrícula y las diez recompensas de tareas lógicas permanecen fijos. Esta es evolución activa por selección, no evolución neutral."},
  {"lesson.richness_limit", "Sequence richness counts distinct ordered sequences present now. It is not a mutation count or every sequence ever seen. More sequences do not establish greater fitness or adaptation. Treat each run as an observation, not a universal outcome.", "La riqueza de secuencias cuenta las secuencias ordenadas distintas presentes ahora. No es un conteo de mutaciones ni todas las secuencias jamás vistas. Más secuencias no establecen mayor aptitud o adaptación. Trate cada ejecución como una observación, no como un resultado universal."},
  {"lessons.mutation_variation.prediction", "Record your prediction", "Registre su predicción"},
  {"lesson.prediction.new_sequences", "Will new sequences appear at 0% mutation? At 1% mutation?", "¿Aparecerán nuevas secuencias al 0% de mutación? ¿Al 1% de mutación?"},
  {"lesson.prediction.richness", "Must sequence richness rise at every update?", "¿Debe aumentar la riqueza de secuencias en cada actualización?"},
  {"lesson.prediction.seeds", "Will runs that start with the same seed follow the same path?", "¿Seguirán las ejecuciones que comienzan con la misma semilla el mismo camino?"},
  {"lesson.learning_record.heading", "Learning record", "Registro de aprendizaje"},
  {"lesson.learning_record.help", "Write a prediction before running, then record what you observed. These notes travel with the saved experiment.", "Escriba una predicción antes de ejecutar, luego registre lo que observó. Estas notas viajan con el experimento guardado."},
  {"lesson.prediction.label", "Prediction", "Predicción"},
  {"lesson.prediction.accessible", "Prediction before running", "Predicción antes de ejecutar"},
  {"lesson.prediction.placeholder", "What do you expect to happen?", "¿Qué espera que ocurra?"},
  {"lesson.observations.label", "Observations", "Observaciones"},
  {"lesson.observations.accessible", "Observation after running", "Observación tras la ejecución"},
  {"lesson.observations.placeholder", "What did the recorded runs show?", "¿Qué mostraron las ejecuciones registradas?"},
  {"experiment.setup.heading", "Experiment setup", "Configuración del experimento"},
  {"experiment.preset.label", "Experiment preset", "Preajuste del experimento"},
  {"experiment.preset.full", "Mutation variation · every update", "Mutación variable · cada actualización"},
  {"experiment.preset.quick", "Quick check · every 10 updates", "Chequeo · cada 10 actualizaciones"},
  {"experiment.treatment.label", "Mutation treatment", "Tratamiento de mutación"},
  {"experiment.preset.zero_mutation", "0% mutation", "0% de mutación"},
  {"experiment.preset.one_percent", "1% mutation", "1% de mutación"},
  {"experiment.mutation.setting", "Per-site mutation setting ({percent}%)", "Configuración de probabilidad de mutación por sitio ({percent}%)"},
  {"experiment.mutation.help", "At reproduction, each copied genome site has the stated chance of being selected for instruction randomization. The replacement instruction can match the instruction that was already there.", "En la reproducción, cada sitio del genoma copiado tiene la probabilidad declarada de ser seleccionado para la aleatorización de instrucciones. La instrucción de reemplazo puede coincidir con la instrucción que ya estaba presente."},
  {"experiment.mutation.help.short", "The setting is the chance of mutation at each copied genome site.", "La configuración es la probabilidad de mutación en cada sitio del genoma copiado."},
  {"experiment.seed.label", "Random seed", "Semilla aleatoria"},
  {"experiment.target.label", "Stop at update", "Detenerse en la actualización"},
  {"experiment.run_to_target", "Run to target", "Ejecutar hasta el objetivo"},
  {"status.paused", "Paused at update {update}", "Pausado en la actualización {update}"},
  {"status.update", "Update {update} of {target}", "Actualización {update} de {target}"},
  {"status.pausing", "Pausing after update {update}", "Pausando después de la actualización {update}"},
  {"status.finished", "Finished at target: update {update}", "Finalizado en el objetivo: actualización {update}"},
  {"population.heading", "Current population", "Población actual"},
  {"metrics.population.organisms", "Organisms", "Organismos"},
  {"metrics.population_count.description", "Number of living organisms.", "Número de organismos vivos."},
  {"metrics.sequence.richness", "Distinct sequences", "Riqueza de secuencias"},
  {"metrics.mutation.per_site_rate", "Per-site mutation setting", "Configuración de probabilidad de mutación por sitio"},
  {"metrics.population_count.label", "Population size (organisms)", "Tamaño de la población (organismos)"},
  {"metrics.population_count.definition", "Number of occupied cells in the same snapshot.", "Número de celdas ocupadas en la misma instantánea."},
  {"metrics.sequence_richness.label", "Sequence richness (distinct sequences)", "Riqueza de secuencias (secuencias distintas)"},
  {"metrics.sequence_richness.definition", "Number of distinct ordered genome sequences present at this update.", "Número de secuencias genómicas ordenadas distintas presentes en esta actualización."},
  {"metrics.ancestor_sequence_fraction.label", "Ancestor sequence (% of population)", "Fracción de secuencia del ancestro (% de la población)"},
  {"metrics.ancestor_sequence_fraction.definition", "Share of organisms whose current sequence exactly matches the original ancestor; this is not ancestry.", "Proporción de organismos cuya secuencia actual coincide exactamente con la del ancestro original; esto no es ascendencia."},
  {"results.heading", "Recorded observations", "Observaciones registradas"},
  {"results.empty", "Start the population to record update 0 and each completed update.", "Inicie la población para registrar la actualización 0 y cada actualización completada."},
  {"results.sample_context", "Run {treatment} per-site mutation · seed {seed} · sample every {interval} update(s). Values are captured at completed update boundaries.", "Ejecutar con {treatment} de mutación por sitio · semilla {seed} · tomar una muestra cada {interval} actualización(es). Los valores se registran al completar cada actualización."},
  {"results.rows.one", "{count} recorded update row", "{count} fila de actualización registrada"},
  {"results.rows.other", "{count} recorded update rows", "{count} filas de actualización registradas"},
  {"results.table.update", "Update", "Actualización"},
  {"results.table.population", "Population (N)", "Población (N)"},
  {"results.table.richness", "Sequence richness (S)", "Riqueza de secuencias (S)"},
  {"results.table.ancestor_fraction", "Ancestor sequence (%)", "Secuencia del ancestro (%)"},
  {"results.chart.population.aria", "Population size by update", "Tamaño de la población por actualización"},
  {"results.chart.richness.aria", "Sequence richness by update", "Riqueza de secuencias por actualización"},
  {"results.chart.ancestor_fraction.aria", "Ancestor sequence fraction by update", "Fracción de secuencia del ancestro por actualización"},
  {"results.chart.color_scale.aria", "Color scale from low to high", "Escala de colores de bajo a alto"},
  {"results.color_legend.heading", "Population colors", "Colores de la población"},
  {"results.color_legend.blank", "Blank", "En blanco"},
  {"results.color_legend.no_colors", "No organism colors are displayed.", "No se muestran colores de organismos."},
  {"results.color_legend.no_scale", "Start the population to establish the scale.", "Inicie la población para establecer la escala."},
  {"results.color_legend.empty", "No organisms are currently in the population.", "No hay organismos actualmente en la población."},
  {"results.color_legend.staged", "Staged organisms", "Organismos en espera"},
  {"results.color_legend.other", "Other genotypes", "Otros genotipos"},
  {"results.color_legend.no_tasks", "No tasks performed", "No se han realizado tareas"},
  {"results.color_legend.more_groups", "{count} more groups ({organisms} organisms)", "{count} grupos más ({organisms} organismos)"},
  {"results.color_mode.blank", "Blank", "En blanco"},
  {"results.color_mode.genotype", "Genotype", "Genotipo"},
  {"results.color_mode.phenotype", "Phenotype", "Fenotipo"},
  {"results.color_mode.gestation_cost", "Gestation Cost", "Costo de Gestación"},
  {"results.color_mode.metabolic_rate", "Metabolic Rate", "Tasa Metabólica"},
  {"results.color_mode.fitness", "Fitness", "Aptitud"},
  {"results.color_mode.description.gestation", "Color organisms by the CPU cycles required to produce their offspring.", "Colorear organismos según los ciclos de CPU necesarios para producir su descendencia."},
  {"results.color_mode.description.metabolism", "Color organisms by metabolic base multiplied by metabolic multiplier.", "Colorear organismos según la tasa metabólica base multiplicada por el multiplicador metabólico."},
  {"results.color_mode.description.fitness", "Color organisms by current metabolic rate divided by gestation cost.", "Colorear organismos según la tasa metabólica actual dividida por el costo de gestación."},
  {"results.color_mode.description.genotype", "Color abundant organisms by identical genome.", "Colorear organismos abundantes según el genoma idéntico."},
  {"results.color_mode.description.phenotype", "Color organisms by the combination of reactions their parent performed.", "Colorear organismos según la combinación de reacciones que realizó su progenitor."},
  {"run_shelf.heading", "Run shelf", "Estantería de ejecución"},
  {"run_shelf.description", "Completed observations remain here when you start another run. A completed run is result-only.", "Las observaciones completas permanecen aquí cuando inicia otra ejecución. Una ejecución completada es solo de resultados."},
  {"run_shelf.empty", "No completed runs yet. Use the three listed seeds in both mutation treatments.", "Aún no hay ejecuciones completadas. Utilice las tres semillas listadas en ambos tratamientos de mutación."},
  {"run_shelf.planned_guidance", "Complete seeds 42, 43, and 44 at both 0% and 1%. The same seed does not pair later random trajectories.", "Complete las semillas 42, 43 y 44 tanto al 0% como al 1%. La misma semilla no empareja trayectorias aleatorias posteriores."},
  {"compare.heading", "Compare completed runs", "Comparar ejecuciones completadas"},
  {"compare.independence", "Each line is an independent stochastic trajectory. The three seeds are reused across treatments as starting values; they do not guarantee paired random histories.", "Cada línea es una trayectoria estocástica independiente. Las tres semillas se reutilizan en los tratamientos como valores iniciales; no garantizan historias aleatorias emparejadas."},
  {"compare.metrics", "Compare population size and exact sequence richness. An endpoint table reports the final sample of every completed run.", "Compare el tamaño de la población y la riqueza de secuencias exacta. Una tabla de puntos finales reporta la muestra final de cada ejecución completada."},
  {"compare.incomplete", "Complete at least two target runs before comparing.", "Complete al menos dos ejecuciones objetivo antes de comparar."},
  {"compare.only_completed", "Only completed runs are overlaid; colors identify treatment. Each line is a single stochastic trajectory.", "Solo se superponen las ejecuciones completadas; los colores identifican el tratamiento. Cada línea representa una única trayectoria estocástica."},
  {"compare.endpoints.heading", "Completed run endpoints", "Puntos finales de las ejecuciones completadas"},
  {"compare.table.run", "Run", "Ejecución"},
  {"compare.table.treatment", "Treatment", "Tratamiento"},
  {"compare.table.seed", "Seed", "Semilla"},
  {"compare.table.update", "Update", "Actualización"},
  {"compare.back", "Back to population and run setup", "Volver a la configuración de la población y la ejecución"},
  {"sequence.heading", "Selected sequence and ancestor", "Secuencia seleccionada y secuencia del ancestro"},
  {"sequence.eyebrow", "Genome comparison", "Comparación de genomas"},
  {"sequence.position_note", "Positions are compared directly; this is not sequence alignment. An insertion or deletion can shift later positions.", "Las posiciones se comparan directamente; esto no es alineación de secuencias. Una inserción o deleción puede desplazar posiciones posteriores."},
  {"sequence.ancestor_unavailable", "The lesson reference ancestor is unavailable for this run.", "La secuencia de ancestro de referencia de la lección no está disponible para esta ejecución."},
  {"sequence.same_instruction", "Same instruction", "Instrucción idéntica"},
  {"sequence.different_instruction", "Different instruction", "Instrucción diferente"},
  {"sequence.only_selected", "Only in selected", "Solo en la selección"},
  {"sequence.only_ancestor", "Only in ancestor", "Solo en el ancestro"},
  {"sequence.position", "Position", "Posición"},
  {"sequence.ancestor", "Ancestor", "Ancestro"},
  {"sequence.selected", "Selected", "Seleccionado"},
  {"sequence.difference", "Difference", "Diferencia"},
  {"sequence.not_present", "Not present", "No presente"},
  {"sequence.showing_first", "Showing the first {shown} of {total} positions. Counts above include both complete sequences.", "Mostrando los primeros {shown} de {total} posiciones. Los conteos superiores incluyen tanto secuencias completas."},
  {"sequence.length", "Sequence length: {count} instructions", "Longitud de secuencia: {count} instrucciones"},
  {"save.experiment", "Save experiment JSON", "Guardar experimento JSON"},
  {"open.experiment", "Open experiment JSON", "Abrir experimento JSON"},
  {"save.pausing", "Pausing at a completed update before saving…", "Pausando en una actualización completada antes de guardar…"},
  {"save.pausing_status", "Pausing at an update boundary before saving.", "Pausando en un límite de actualización antes de guardar."},
  {"save.paused_required", "Save is available at a paused update boundary.", "Guardar está disponible en un límite de actualización pausado."},
  {"save.success", "Experiment, notes, and run history downloaded as JSON.", "Experimento, notas e historial de ejecución descargados como JSON."},
  {"open.invalid_file", "This experiment file is invalid or incompatible. Your current work is unchanged.", "Este archivo de experimento es inválido o incompatible. Su trabajo actual no ha cambiado."},
  {"open.pause_status", "Pausing at an update boundary before opening the experiment.", "Pausando en un límite de actualización antes de abrir el experimento."},
  {"open.success", "Experiment and validated checkpoint opened.", "Experimento y punto de control validado abiertos."},
  {"open.failure_prefix", "Experiment not loaded: {reason}", "Experimento no cargado: {reason}"},
  {"export.data", "Export completed data CSV", "Exportar datos completados CSV"},
  {"export.success", "Completed run samples downloaded as CSV.", "Las muestras de la ejecución completada se descargaron como CSV."},
  {"errors.mutation.range", "Enter a per-site mutation setting from {minimum}% to {maximum}%.", "Ingrese una probabilidad de mutación por sitio desde {minimum}% hasta {maximum}%."},
  {"errors.run.failed", "The run could not continue: {reason}", "La ejecución no pudo continuar: {reason}"},
  {"glossary.update", "update", "actualización"},
  {"glossary.generation", "generation", "generación"},
  {"glossary.sequence_richness", "sequence richness", "riqueza de secuencias"},
  {"glossary.ancestor_sequence", "ancestor sequence", "secuencia del ancestro"},
  {"glossary.ancestry", "ancestry", "ascendencia"},
  {"glossary.per_site_mutation", "per-site mutation setting", "probabilidad de mutación por sitio"},
  {"glossary.fitness", "fitness", "aptitud"},
  {"experiment.mutation.label", "Per-site mutation setting (%)", "Probabilidad de mutación por sitio (%)"},
  {"shell.selected_cell", "Selected cell", "Celda seleccionada"},
  {"shell.viewer_chooser", "Viewer chooser", "Selector de vista"},
  {"population.size", "Population size", "Tamaño de la población"},
  {"shell.save", "Save", "Guardar"},
  {"shell.open", "Open", "Abrir"},
  {"shell.export", "Export", "Exportar"},
  {"organism.toolbar.rewind.aria", "Rewind organism execution", "Rebobinar la ejecución del organismo"},
  {"organism.toolbar.step.aria", "Execute one organism instruction", "Ejecutar una instrucción del organismo"},
  {"organism.toolbar.play.aria", "Play at two instructions per second", "Ejecutar a dos instrucciones por segundo"},
  {"organism.toolbar.pause.aria", "Pause organism execution", "Pausar la ejecución del organismo"},
  {"organism.toolbar.fast_forward.aria", "Fast-forward at twenty instructions per second", "Avance rápido a veinte instrucciones por segundo"},
  {"organism.toolbar.rewind.title", "Rewind", "Rebobinar"},
  {"organism.toolbar.step.title", "Step (Space)", "Paso (Espacio)"},
  {"organism.toolbar.play.title", "Play (2 instructions per second)", "Reproducir (2 instrucciones por segundo)"},
  {"organism.toolbar.fast_forward.title", "Fast-forward (20 instructions per second)", "Avance rápido (20 instrucciones por segundo)"},
  {"organism.toolbar.view_offspring", "View offspring →", "Ver descendencia →"},
  {"organism.freezer.label", "Organism", "Organismo"},
  {"organism.freezer.placeholder", "Choose from freezer…", "Elegir del almacén…"},
  {"organism.freezer.accessible", "Choose an organism from the freezer", "Elige un organismo del almacén"},
  {"organism.timeline.label", "Execution position", "Posición de ejecución"},
  {"organism.timeline.accessible", "Organism execution position", "Posición de ejecución del organismo"},
  {"population.color_mode.accessible", "Population color mode", "Modo de color de la población"},
  {"population.color_mode.title", "Color organisms by", "Colorear organismos por"},
  {"organism.empty.heading", "Select an organism first", "Seleccione un organismo primero"},
  {"organism.empty.help", "Select an organism from the freezer (above) or return to Population mode and select an occupied cell.", "Seleccione un organismo del almacén (arriba) o regrese al modo Población y seleccione una celda ocupada."},
  {"organism.cycle.heading", "Single life cycle", "Ciclo de vida único"},
  {"organism.cycle.instructions_executed", "instructions executed", "instrucciones ejecutadas"},
  {"organism.genome.eyebrow", "Execution map", "Mapa de ejecución"},
  {"organism.genome.heading", "Genome", "Genoma"},
  {"organism.genome.instruction_count", "instructions", "instrucciones"},
  {"organism.genome.end", "end of genome", "fin del genoma"},
  {"organism.status.complete", "Life cycle complete", "Ciclo de vida completo"},
  {"organism.status.offspring", "Offspring produced · {count} instructions. Use “View offspring” above to start it with fresh hardware.", "Descendencia producida · {count} instrucciones. Use «Ver descendencia» para iniciarla con hardware nuevo."},
  {"organism.status.preview_limit", "Preview limit reached", "Límite de vista previa alcanzado"},
  {"organism.status.continues", "Execution continues", "La ejecución continúa"},
  {"organism.status.no_offspring", "No offspring was produced in the first {count} instructions.", "No se produjeron descendientes en las primeras {count} instrucciones."},
  {"organism.instruction.just_executed_at", "Just executed at {update}", "Ejecutado recientemente en {update}"},
  {"organism.instruction.just_executed", "Just executed", "Ejecutado recientemente"},
  {"organism.instruction.nothing_yet", "Nothing yet", "Aún nada"},
  {"organism.instruction.start_help", "Use Step, Play, or Fast-forward to begin this life cycle.", "Use Paso, Reproducir o Avanzar rápido para iniciar este ciclo de vida."},
  {"organism.instruction.about_to_execute", "About to execute at {update}", "A punto de ejecutar en {update}"},
  {"organism.registers.heading", "Registers", "Registros"},
  {"organism.stacks.heading", "Stacks", "Pilas"},
  {"organism.stack.label", "Stack", "Pila"},
  {"organism.memory.eyebrow", "Working state", "Estado de trabajo"},
  {"organism.memory.heading", "Memory", "Memoria"},
  {"organism.memory.copied", "Copied", "Copiados"},
  {"organism.memory.errors", "Errors", "Errores"},
  {"organism.tasks.eyebrow", "Life-cycle progress", "Progreso del ciclo de vida"},
  {"organism.tasks.heading", "Tasks", "Tareas"},
  {"organism.tasks.empty", "No configured reaction tasks are performed in this life cycle.", "No se realizan tareas de reacción configuradas en este ciclo de vida."},
  {"organism.traits.eyebrow", "Starting phenotype", "Fenotipo inicial"},
  {"organism.traits.heading", "Organism traits", "Características del organismo"},
  {"organism.traits.empty", "No printable traits.", "No hay rasgos imprimibles."},
  {"organism.stats.empty", "Select an occupied population cell to inspect its organism.", "Seleccione una celda de población ocupada para inspeccionar su organismo."},
  {"organism.stats.active", "Active organism", "Organismo activo"},
  {"organism.stats.phenotype", "Phenotype", "Fenotipo"},
  {"organism.stats.hardware", "Hardware", "Hardware"},
  {"organism.stats.executed", "Executed", "Ejecuciones"},
  {"organism.stats.heads", "Heads", "Cabezas"},
  {"organism.stats.memory", "Nonzero memory", "Memoria con valores distintos de cero"},
  {"organism.stats.memory.empty", "All locations are zero.", "Todas las ubicaciones son cero."},
  {"organism.genome.next", "NEXT", "SIGUIENTE"},
  {"organism.head.follow", "Follow", "Seguir"},
  {"organism.head.stop_following", "Stop following", "Dejar de seguir"},
  {"freezer.name.aria", "Name for {name}; double-click to edit", "Nombre: {name}; haga doble clic para editar"},
  {"freezer.instructions.one", "{count} instruction", "{count} instrucción"},
  {"freezer.instructions.other", "{count} instructions", "{count} instrucciones"},
  {"freezer.organism.download.aria", "Download {name} organism file", "Descargar el archivo del organismo {name}"},
  {"freezer.organism.download.title", "Download {name} as .org", "Descargar {name} como archivo .org"},
  {"freezer.remove", "Remove {name}", "Quitar {name}"},
  {"freezer.configuration.download.aria", "Download {name} configuration file", "Descargar el archivo de configuración {name}"},
  {"freezer.configuration.download.title", "Download {name} as .cfg", "Descargar {name} como archivo .cfg"},
  {"freezer.configuration.summary", "Reactions: {reactions}; events: {events}; organisms: {organisms}", "Reacciones: {reactions} · eventos: {events} · organismos: {organisms}"},
  {"configuration.settings.tab", "Settings", "Ajustes"},
  {"configuration.environment.tab", "Environment", "Entorno"},
  {"configuration.events.tab", "Events", "Eventos"},
  {"freezer.name.title", "Double-click to rename", "Haga doble clic para cambiar el nombre"},
  {"freezer.intro", "Double-click a name to edit it. Drag organisms between this freezer and the grid.", "Haga doble clic en un nombre para editarlo. Arrastre organismos entre el almacén y la cuadrícula."},
  {"freezer.organisms.help", "Genomes that can seed a new dish.", "Genomas que pueden iniciar una población nueva."},
  {"freezer.load", "Load", "Cargar"},
  {"freezer.organisms.empty", "No frozen organisms.", "No hay organismos guardados."},
  {"freezer.configurations.help", "Configured dishes before a run.", "Configuraciones de población previas a una ejecución."},
  {"freezer.configurations.empty", "No frozen configurations.", "No hay configuraciones guardadas."},
  {"freezer.checkpoints.help", "Portable full-population files; not stored in this browser.", "Archivos portátiles con la población completa; no se guardan en este navegador."},
  {"freezer.save.checkpoint", "Save Checkpoint", "Guardar punto"},
  {"freezer.load.checkpoint", "Load checkpoint file", "Cargar archivo de punto de control"},
  {"freezer.checkpoints.empty", "Choose a checkpoint file to resume a saved run.", "Elija un archivo de punto de control para reanudar una ejecución guardada."},
  {"configuration.heading", "Configuration", "Configuración"},
  {"configuration.advanced.on", "Advanced: On", "Avanzado: sí"},
  {"configuration.advanced.off", "Advanced: Off", "Avanzado: no"},
  {"configuration.advanced.title", "Show or hide advanced settings", "Mostrar u ocultar los ajustes avanzados"},
  {"configuration.reset", "Reset", "Restablecer"},
  {"configuration.reset.title", "Reset this configuration tab to its web defaults", "Restablecer los valores iniciales de esta pestaña"},
  {"configuration.settings.intro", "Settings for the current population.", "Ajustes de la población actual."},
  {"freezer.configurations.heading", "Configurations", "Configuraciones"},
  {"freezer.save.configuration", "Save Configuration", "Guardar configuración"},
  {"freezer.checkpoints.heading", "Checkpoints", "Puntos de control"},
  {"shell.sidepanel.configure.accessible", "Configure", "Ajustes"},
  {"freezer.status.saved", "Saved in this browser.", "Guardado en este navegador."},
  {"freezer.status.session_saved", "Saved for this session; browser storage is unavailable or full.", "Guardado durante esta sesión; el almacenamiento del navegador no está disponible o está lleno."},
  {"freezer.status.loaded", "Loaded organisms and configurations from this browser.", "Se cargaron organismos y configuraciones guardados en este navegador."},
  {"population.palette.label", "Continuous color map", "Mapa de colores continuos"},
  {"population.palette.title", "Choose the numeric color map", "Elija la paleta para valores numéricos"},
  {"population.palette.gnuplot2", "Gnuplot 2", "Gnuplot 2"},
  {"population.palette.viridis", "Viridis", "Viridis"},
  {"population.palette.cubehelix", "Cubehelix", "Cubehelix"},
  {"results.population_history.title", "Population size over time", "Tamaño de la población a lo largo del tiempo"},
  {"results.population_history.axis", "Organisms", "Organismos"},
  {"results.richness_history.title", "Sequence richness over time", "Riqueza de secuencias a lo largo del tiempo"},
  {"results.richness_history.axis", "Distinct sequences", "Secuencias distintas"},
  {"results.ancestor_history.title", "Ancestor sequence over time", "Secuencia ancestral a lo largo del tiempo"},
  {"results.ancestor_history.axis", "Percent of population", "Porcentaje de la población"},
}};

[[nodiscard]] constexpr const SpanishEntry * FindSpanish(std::string_view id) noexcept {
  for (const auto & entry : SPANISH_CANDIDATE) if (entry.id == id) return &entry;
  return nullptr;
}

[[nodiscard]] constexpr std::string_view SpanishText(std::string_view source) noexcept {
  const SpanishEntry * match = nullptr;
  for (const auto & entry : SPANISH_CANDIDATE) {
    if (entry.source != source || entry.id.starts_with("glossary.")) continue;
    if (!match) match = &entry;
    else if (match->value != entry.value) return source; // Require an ID for ambiguous text.
  }
  return match ? match->value : source;
}
} // namespace avida::web::localization
